// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { existsSync, readFileSync } from "fs";
import { resolve } from "path";
import { parse } from "dotenv";
import { defineConfig } from "prisma/config";

const envPath = resolve(__dirname, ".env");
if (existsSync(envPath)) {
  const parsed = parse(readFileSync(envPath, "utf-8"));
  if (parsed.DATABASE_URL) {
    process.env.DATABASE_URL = parsed.DATABASE_URL;
  }
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
