const TZ_TO_COUNTRY: Record<string, string> = {
  "Europe/Moscow": "RU",
  "Europe/Kaliningrad": "RU",
  "Europe/Simferopol": "RU",
  "Europe/Volgograd": "RU",
  "Europe/Kirov": "RU",
  "Europe/Astrakhan": "RU",
  "Europe/Saratov": "RU",
  "Europe/Ulyanovsk": "RU",
  "Europe/Samara": "RU",
  "Asia/Yekaterinburg": "RU",
  "Asia/Omsk": "RU",
  "Asia/Novosibirsk": "RU",
  "Asia/Barnaul": "RU",
  "Asia/Tomsk": "RU",
  "Asia/Novokuznetsk": "RU",
  "Asia/Krasnoyarsk": "RU",
  "Asia/Irkutsk": "RU",
  "Asia/Chita": "RU",
  "Asia/Yakutsk": "RU",
  "Asia/Khandyga": "RU",
  "Asia/Vladivostok": "RU",
  "Asia/Ust-Nera": "RU",
  "Asia/Magadan": "RU",
  "Asia/Sakhalin": "RU",
  "Asia/Srednekolymsk": "RU",
  "Asia/Kamchatka": "RU",
  "Asia/Anadyr": "RU",
  "Europe/Minsk": "BY",
  "Europe/Kyiv": "UA",
  "Europe/Kiev": "UA",
  "Asia/Almaty": "KZ",
  "Asia/Qyzylorda": "KZ",
  "Asia/Aqtobe": "KZ",
  "Asia/Aqtau": "KZ",
  "Asia/Oral": "KZ",
  "Asia/Tashkent": "UZ",
  "Asia/Samarkand": "UZ",
  "Asia/Tbilisi": "GE",
  "Asia/Yerevan": "AM",
  "Asia/Baku": "AZ",
  "Europe/Chisinau": "MD",
  "Europe/Riga": "LV",
  "Europe/Tallinn": "EE",
  "Europe/Vilnius": "LT",
  "Europe/Warsaw": "PL",
  "Europe/Berlin": "DE",
  "Europe/Paris": "FR",
  "Europe/London": "GB",
  "Europe/Rome": "IT",
  "Europe/Madrid": "ES",
  "Europe/Istanbul": "TR",
  "Asia/Dubai": "AE",
  "Asia/Shanghai": "CN",
  "Asia/Tokyo": "JP",
  "Asia/Seoul": "KR",
  "Asia/Bangkok": "TH",
  "Asia/Singapore": "SG",
  "Asia/Kolkata": "IN",
  "America/New_York": "US",
  "America/Chicago": "US",
  "America/Denver": "US",
  "America/Los_Angeles": "US",
  "America/Toronto": "CA",
  "Australia/Sydney": "AU",
};

export function countryCodeFromTimezone(tz: string | null | undefined): string | null {
  if (!tz) return null;
  const trimmed = tz.trim();
  if (!trimmed || trimmed.length > 64) return null;
  return TZ_TO_COUNTRY[trimmed] ?? null;
}
